spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/compliance}
    username: ${DB_USER:dev}
    password: ${DB_PASS:dev}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
